using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataAccessLayer.Models
{
    public class Exam
    {
        public int Id { get; set; }

        public string Title { get; set; }

        //public int Duration { get; set; } // In minutes
        //public DateTime StartTime { get; set; } // When exam is scheduled to begin

        //public string Note { get; set; } // Optional additional info (e.g., room number, instructions)

        public int CourseId { get; set; }
        public int ProfessorId { get; set; }
        public string Metadata { get; set; } // Contains JSON with metadata
        public int TotalQuestions { get; set; }
        //public bool IsAutoGenerated { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

        public Course Course { get; set; }
        public User Professor { get; set; }

      //  public ICollection<ExamQuestion> ExamQuestions { get; set; }
        public List<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>(); // Ensure initialization
        public ExamSettings ExamSettings { get; set; }
    }

}
