using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PresentationLayer.ViewModels
{
    public class QuestionAddViewModel
    {
        // Optional, as it is typically auto-generated by the database.
        public int Id { get; set; }

        [Required(ErrorMessage = " Please enter a Question text.")]
        public string Text { get; set; }

        [Required(ErrorMessage = "Question type is required.")]
        public int QuestionTypeId { get; set; }

        [Required(ErrorMessage = "Difficulty level is required.")]
        public int DifficultyLevelId { get; set; }

        [Required(ErrorMessage = "Professor ID is required.")]
        public int professorId { get; set; }

        [Required(ErrorMessage = "Please enter a Category name.")]
       // [Range(1, int.MaxValue, ErrorMessage = "Please select a valid category.")]
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Please enter a course name.")]
       // [Range(1, int.MaxValue, ErrorMessage = "Please select a valid course.")]
        public int CourseId { get; set; }

        [Required(ErrorMessage = "Please provide at least one answer.")]
        public List<AnswerAddViewModel> Answers { get; set; } = new List<AnswerAddViewModel>();

        [Required(ErrorMessage = "Please select the correct answer.")]
        public int? CorrectAnswerIndex { get; set; }
    }

    

   
}
