using BusinessLogicLayer.Dtos.LectureDto;
using BusinessLogicLayer.Dtos;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PresentationLayer.ViewModels
{
    public class QuestionAddViewModel
    {
        // Optional, as it is typically auto-generated by the database.
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter a Question text.")]
        public string Text { get; set; }

        [Required(ErrorMessage = "Question type is required.")]
        public int QuestionTypeId { get; set; }

        [Required(ErrorMessage = "Difficulty level is required.")]
        public int DifficultyLevelId { get; set; }

        [Required(ErrorMessage = "Professor ID is required.")]
        public int professorId { get; set; }

       
        public int? CategoryId { get; set; } // Selected Category ID

        [Required(ErrorMessage = "Please enter a course name.")]
        public int CourseId { get; set; } // Selected Course ID

        [Required(ErrorMessage = "Please provide at least one answer.")]
        public List<AnswerAddViewModel> Answers { get; set; } = new List<AnswerAddViewModel>();

        [Required(ErrorMessage = "Please select the correct answer.")]
        public int? CorrectAnswerIndex { get; set; }

        //[Required(ErrorMessage = "Lecture is required.")]
        //public int LectureId { get; set; } // Selected Lecture ID

        [Required(ErrorMessage = "Lecture name is required.")]
        public string LectureName { get; set; } // Instead of LectureId


        // Collections for dropdowns (bind categories, courses, lectures)
        public List<CategoryGetDto> Categories { get; set; } = new List<CategoryGetDto>(); // All available categories
        public List<CourseGetDto> Courses { get; set; } = new List<CourseGetDto>();       // All available courses
      //  public List<LectureGetDto> Lectures { get; set; } = new List<LectureGetDto>();   // All available lectures
        public List<DifficultyLevelDto> DifficultyLevels { get; set; } = new List<DifficultyLevelDto>();
        


    }
}
